version: '3'
services:
  app:
    restart: always
    build: .
    command: sh container/start.sh
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - static:/app/static
    env_file: env

  autotests:
    build: .
    command: sh container/autotests.sh
    links:
      - postgres:postgres
    env_file: env

  seed:
    build: .
    command: sh container/seed.sh
    links:
      - postgres:postgres
    env_file: env

  runserver:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - app:app
    volumes:
      - static:/data/static

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - env
    expose:
      - "5432"

volumes:
  static:

