# Generated by Django 2.1 on 2018-10-15 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20181015_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chatbot.QuestionList'),
            preserve_default=False,
        ),
    ]
